"""Initial

Revision ID: 264d1a7838cc
Revises: 
Create Date: 2022-09-09 16:20:41.900026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import  Enum


# revision identifiers, used by Alembic.
revision = '264d1a7838cc'
down_revision = None
branch_labels = None
depends_on = None

ItemType = Enum('FILE', 'FOLDER', name='type')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('type', ItemType, nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__items'))
    )
    op.create_index(op.f('ix__items__item_id'), 'items', ['item_id'], unique=False)
    op.create_index(op.f('ix__items__parent_id'), 'items', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__items__parent_id'), table_name='items')
    op.drop_index(op.f('ix__items__item_id'), table_name='items')
    op.drop_table('items')

    ItemType.drop(op.get_bind())
    # ### end Alembic commands ###
