version: '3.7'
services:
  postgres:
    restart: always
    image: postgres:14
    environment:
      POSTGRES_DB: "disk"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - - /var/lib/postgresql/data:/var/lib/postgresql/data

  migrations_service:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DISK_PG_URL=postgresql://db_user:12345@postgres:5432/disk
    command: ["disk_app-db", "upgrade", "head"]

  disk_service:
    restart: always
    depends_on:
      - postgres
      - migrations_service
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:8080"
    environment:
      - DISK_PG_URL=postgresql://db_user:12345@postgres:5432/disk
    command: ["disk_app-api"]
